# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://github.com/pre-commit/pre-commit-hooks for more hooks by pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        types: [python]
        args: [--line-length=120]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        types: [python]
        # E203: whitespace before ':'
        # W503: line break before binary operator
        args: [--max-line-length=120, "--ignore=W503,E203"]
        additional_dependencies: ['flake8-print']
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        types: [python]
        args: [--line-length, "120", --profile, black, --filter-files]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'
    hooks:
    -   id: mypy
        args: [--strict, --explicit-package-bases, --allow-untyped-decorators]
